server:
  address: localhost
  port: 9000

spring:
  application:
    name: demo
  datasource:
    driver-class-name: org.h2.Driver
    username: root
    password: 1234
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2

# driver-class-name: com.mysql.jdbc.Driver # mysql 5??
